parameters:
    mercure_default_url: 'http://127.0.0.1:3000/.well-known/mercure'
    mercure_default_jwt_secret: '!ChangeThisMercureHubJWTSecretKey!'

mercure:
    hubs:
        default:
            url: '%env(default:mercure_default_url:MERCURE_URL)%'
            public_url: '%env(default:mercure_default_url:MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(default:mercure_default_jwt_secret:MERCURE_JWT_SECRET)%'
                publish:
                    - '*'
                subscribe:
                    - '*'
